# Generated by Django 5.1.4 on 2024-12-14 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('no_refund', 'No Refund'), ('partial_refund', 'Partial Refund'), ('full_refund', 'Full Refund')], default='no_refund', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_status',
            field=models.CharField(choices=[('not_refunded', 'Not Refunded'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='not_refunded', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='coursechatroom',
            unique_together={('course',)},
        ),
    ]
