# Generated by Django 5.1.2 on 2024-10-28 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_enrolment_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='date_enrolled',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
