# Generated by Django 5.1.3 on 2024-11-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_address_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='address',
            name='student',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated_at',
        ),
    ]
