# Generated by Django 5.1.3 on 2024-11-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_address_options_alter_address_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(default='dsfds', max_length=100),
            preserve_default=False,
        ),
    ]
