# Generated by Django 5.1.3 on 2024-11-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
