# Generated by Django 5.1.3 on 2024-11-13 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayOrders',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('rzr_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('rzr_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='razor_orders', to='students.order')),
            ],
        ),
    ]
