services:
  web:
    build: .
    command: sh -c "python manage.py migrate && uvicorn eduskill.asgi:application --host 0.0.0.0 --port 8000"
    container_name: eduskill1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  celery:
    build: .
    command: celery -A eduskill.celery:app worker --loglevel=info
    container_name: celery1
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
