# Generated by Django 5.1.2 on 2024-10-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUD', 'Student'), ('TUTR', 'Tutor')], max_length=4),
        ),
    ]
