# Generated by Django 5.1.2 on 2024-10-11 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_category_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_published',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='courses_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_limit',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Saved as Draft'), ('pending_approval', 'Saved for Approval'), ('published', 'Published Public')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in hours', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
