# Generated by Django 5.1.2 on 2024-10-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_rename_is_published_course_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='duration',
        ),
    ]
