# Generated by Django 5.1.2 on 2024-10-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_remove_videocontent_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
