# Generated by Django 5.1.2 on 2024-10-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_alter_teacher_bio_alter_teacher_qualifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='is_published',
            new_name='is_acive',
        ),
    ]
