# Generated by Django 5.1.2 on 2024-10-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_rename_is_published_lesson_is_acive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='is_acive',
            new_name='is_active',
        ),
    ]
