# Generated by Django 5.1.2 on 2024-10-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_rename_is_acive_lesson_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Saved as Draft'), ('pending_approval', 'Saved for Approval'), ('published', 'Published Public'), ('blocked', 'Blocked')], db_index=True, default='draft', max_length=20),
        ),
    ]
