# Generated by Django 5.1.2 on 2024-10-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_videocontent_hls_videocontent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='hls',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
