# Generated by Django 5.1.2 on 2024-10-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_alter_videocontent_hls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='lessons/thumbnails'),
        ),
    ]
